#!/bin/sh

set -ue

HERE="$(cd "$(dirname "$0")"; pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

copy=""

while [ "$#" -ne 0 ]; do
	case "$1" in
		"-c" | "--copy" ) copy="1"; shift 1;;
		* ) printf "usage: %s [--copy]\n" "$0" >&2; exit 1;;
	esac
done

run() {
	printf "\$ %s\n" "$*"
	"$@"
}

put() {
	parent="$(dirname "$2")"
	if [ "$parent" != "$HOME" ]; then
		run mkdir -p "$parent"
	fi
	if [ -n "$copy" ]; then
		run cp --remove-destination "$HERE/$1" "$2"
	else
		run ln -sf "$HERE/$1" "$2"
	fi
}

put "tmux.conf" "$HOME/.tmux.conf"
put "global.vimrc" "$HOME/.vimrc"
put "global.zshrc" "$HOME/.zshrc"

put "global.gitconfig" "$CONFIG/git/config"
put "global.gitignore" "$CONFIG/git/ignore"
put "wezterm.lua" "$CONFIG/wezterm/wezterm.lua"
