#!/usr/bin/env sh

set -ue

BASE_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
echo "${BASE_DIR}/scripts/functions"
. "${BASE_DIR}/scripts/functions"

clone() {
	clone_into "${BASE_DIR}/files/$1" "$2"
}

install_files() {
	clone "tmux.conf" "${HOME}/.tmux.conf"
	clone "global.vimrc" "${HOME}/.vimrc"
	clone "global.zshrc" "${HOME}/.zshrc"

	clone "global.gitconfig" "${CONFIG}/git/config"
	clone "global.gitignore" "${CONFIG}/git/ignore"
	clone "wezterm.lua" "${CONFIG}/wezterm/wezterm.lua"

	clone "k9s.config.yaml" "${PLATFORM_CONFIG}/k9s/config.yaml"
	clone "k9s.default-skin.yaml" "${PLATFORM_CONFIG}/k9s/skins/default-skin.yaml"
}

main() {
	parse_args "$@"

	info "installing files..."
	install_files

	if [ -n "${INSTALL_TOOLS}" ]; then
		info "installing tools..."
	fi

	info "installation completed."
}

main "$@"
