#!/usr/bin/env sh

set -ue

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ "$(uname)" = "Darwin" ]; then
	NATIVE_CONFIG="$HOME/Library/Application Support"
else
	NATIVE_CONFIG="$CONFIG"
fi
LOCAL_BIN="$HOME/.local/bin"

copy=""
no_files=""
no_tools=""

usage() {
	printf "usage: %s [--copy] [--no-files] [--no-tools] [--help]\n" "$(basename "$0")" >&2
}

while [ "$#" -ne 0 ]; do
	case "$1" in
		"-c" | "--copy" ) copy="1"; shift 1;;
		"--no-files" ) no_files="1"; shift 1;;
		"--no-tools" ) no_tools="1"; shift 1;;
		"-h" | "--help" ) usage; exit 0;;
		* ) usage; exit 1;;
	esac
done

run() {
	printf "\$ %s\n" "$*"
	"$@"
}

put() {
	local src="$BASE_DIR/$1"
	local dest="$2"
	local dest_dir
	dest_dir="$(dirname "$dest")"
	if [ "$dest_dir" != "$HOME" ]; then
		run mkdir -p "$dest_dir"
	fi
	if [ -n "$copy" ]; then
		run cp --remove-destination "$src" "$dest"
	else
		run ln -sf "$src" "$dest"
	fi
}

install_from_github_raw() {
	local repo="$1"
	local path="$2"
	local name="${3:-"$(basename "$path")"}"
	local dest="$LOCAL_BIN/$name"
	local url="https://raw.githubusercontent.com/$repo/HEAD/$path"
	run mkdir -p "$(dirname "$dest")"
	run curl -sSLf "$url" -o "$dest"
	run chmod +x "$dest"
}

files() {
	put "files/tmux.conf" "$HOME/.tmux.conf"
	put "files/global.vimrc" "$HOME/.vimrc"
	put "files/global.zshrc" "$HOME/.zshrc"

	put "files/global.gitconfig" "$CONFIG/git/config"
	put "files/global.gitignore" "$CONFIG/git/ignore"
	put "files/wezterm.lua" "$CONFIG/wezterm/wezterm.lua"

	put "files/k9s.config.yaml" "$NATIVE_CONFIG/k9s/config.yaml"
	put "files/k9s.default-skin.yaml" "$NATIVE_CONFIG/k9s/skins/default-skin.yaml"
}

tools() {
	install_from_github_raw "wafrelka/workspace" "workspace"
	install_from_github_raw "wafrelka/git-get" "git-get"
	install_from_github_raw "wafrelka/gist" "gist"
	install_from_github_raw "wafrelka/nap" "nap"
}

if [ -z "$no_files" ]; then
	files
fi

if [ -z "$no_tools" ]; then
	tools
fi
